# Generated by Django 5.2 on 2025-11-11 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0019_remove_batchenrollment_final_grade_delete_grade'),
        ('student', '0005_alter_student_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_passed', models.BooleanField(default=False)),
                ('was_present', models.BooleanField(default=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True)),
                ('result_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academy.batchenrollment')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
                'ordering': ['-obtained_marks'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=50, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When student started the exam')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When student submitted the exam', null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('timeout', 'Timed Out'), ('interrupted', 'Interrupted')], default='in_progress', max_length=15)),
                ('time_spent_minutes', models.PositiveIntegerField(default=0, help_text='Total time spent in minutes')),
                ('is_time_extended', models.BooleanField(default=False, help_text='Whether extra time was granted')),
                ('extended_time_minutes', models.PositiveIntegerField(default=0, help_text='Extra time granted in minutes')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Student IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information')),
            ],
            options={
                'verbose_name': 'Student Exam Session',
                'verbose_name_plural': 'Student Exam Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('exam_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pass_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exam_id', models.CharField(blank=True, editable=False, help_text='Unique ID for the Exam', max_length=20, null=True, unique=True)),
                ('exam_type', models.CharField(choices=[('paper', 'Paper Based'), ('online', 'Online')], default='paper', help_text='Type of exam', max_length=10)),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('results_published', models.BooleanField(default=False)),
                ('result_published_at', models.DateTimeField(blank=True, null=True)),
                ('sms_sent', models.BooleanField(default=False)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('app_notification_sent', models.BooleanField(default=False)),
                ('app_notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academy.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='OnlineExamResult',
            fields=[
                ('examresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exam.examresult')),
                ('auto_graded_marks', models.DecimalField(decimal_places=2, default=0, help_text='Marks from auto-graded questions', max_digits=6)),
                ('manual_graded_marks', models.DecimalField(decimal_places=2, default=0, help_text='Marks from manually graded questions', max_digits=6)),
                ('total_questions_attempted', models.PositiveIntegerField(default=0, help_text='Number of questions attempted')),
                ('total_questions', models.PositiveIntegerField(default=0, help_text='Total number of questions in exam')),
                ('is_auto_processed', models.BooleanField(default=False, help_text='Whether auto-grading is complete')),
                ('is_manual_grading_complete', models.BooleanField(default=False, help_text='Whether manual grading is complete')),
            ],
            options={
                'verbose_name': 'Online Exam Result',
                'verbose_name_plural': 'Online Exam Results',
            },
            bases=('exam.examresult',),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='student.student'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examresult',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.grade'),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('text_answer', models.TextField(blank=True, help_text='Text answer for short answer/essay questions')),
                ('answered_at', models.DateTimeField(auto_now_add=True, help_text='When answer was submitted')),
                ('last_modified_at', models.DateTimeField(auto_now=True, help_text='When answer was last modified')),
                ('is_correct', models.BooleanField(blank=True, help_text='Whether answer is correct (auto-calculated for MCQ)', null=True)),
                ('awarded_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Marks awarded for this answer', max_digits=5, null=True)),
                ('is_graded', models.BooleanField(default=False, help_text='Whether answer has been manually graded')),
                ('graded_at', models.DateTimeField(blank=True, help_text='When answer was graded', null=True)),
                ('grader_remarks', models.TextField(blank=True, help_text='Grader comments/feedback')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Answer',
                'verbose_name_plural': 'Student Answers',
                'ordering': ['session', 'question__question_order'],
            },
        ),
    ]
