# Generated by Django 5.2 on 2025-11-11 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0019_remove_batchenrollment_final_grade_delete_grade'),
        ('exam', '0001_initial'),
        ('question', '0001_initial'),
        ('student', '0005_alter_student_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='question.question'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='question.questionoption'),
        ),
        migrations.AddField(
            model_name='studentexamsession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentexamsession',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='academy.batchenrollment'),
        ),
        migrations.AddField(
            model_name='studentexamsession',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='studentexamsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='student.student'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.studentexamsession'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('batch', 'title'), name='unique_exam_title_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('pass_marks__lte', models.F('total_marks'))), name='pass_marks_not_greater_than_total'),
        ),
        migrations.AddField(
            model_name='onlineexamresult',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='exam.studentexamsession'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='unique_result_per_exam_student'),
        ),
        migrations.AddConstraint(
            model_name='studentexamsession',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='unique_session_per_exam_student'),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_answer_per_session_question'),
        ),
    ]
