# Generated by Django 5.2 on 2025-11-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.CharField(choices=[('bangla', 'Bangla'), ('english', 'English'), ('mathematics', 'Mathematics'), ('biology', 'Biology'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('ict', 'Information and Communications Technology')], default='bangla', help_text='Subject', max_length=50),
        ),
    ]
