# Generated by Django 6.0 on 2025-12-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_exam_archived_by_examresult_archived_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exam',
            name='pass_marks_not_greater_than_total',
        ),
    ]
