# Generated by Django 6.0 on 2025-12-07 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0025_alter_academy_established_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, help_text='Teacher profile image', null=True, upload_to='teacher_profiles/')),
                ('full_name', models.CharField(help_text="Teacher's full name (e.g., Dr. Sadia Ekter)", max_length=255)),
                ('title', models.CharField(blank=True, help_text='Professional title (e.g., Mathematics Lead, Science Director)', max_length=255, null=True)),
                ('bio', models.TextField(blank=True, help_text="Teacher's biography/about section", null=True)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of teaching experience')),
                ('location', models.CharField(blank=True, help_text='Location (e.g., San Francisco, USA)', max_length=255, null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL', null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this teacher is featured on landing page')),
                ('is_available', models.BooleanField(default=True, help_text='Whether teacher is currently available for booking')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this teacher is active/visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Teacher creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Teacher update timestamp')),
                ('academy', models.ForeignKey(help_text='One teacher per academy', on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='academy.academy')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
