# Generated by Django 5.2 on 2025-05-03 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_role_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid contact number.', regex='^\\+?\\d{7,15}$')], verbose_name='Mobile number'),
        ),
    ]
