# Generated by Django 5.2 on 2025-09-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_permission_menu_rolemenupermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemenupermission',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='account.permission'),
        ),
    ]
