# Generated by Django 5.2 on 2025-10-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_menu_options_menu_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rolemenupermission',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
