# Generated by Django 5.2 on 2025-10-20 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_menu_remarks_rolemenupermission_remarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['name', 'order']},
        ),
    ]
