# Generated by Django 6.0 on 2025-12-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_recoveryotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryotp',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
