# Generated by Django 6.0 on 2025-12-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemenupermission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
