services:
  web:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    container_name: classmate_web
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - ./.envs/.production/.env.production
      

  db:
    image: postgres:18
    restart: always
    container_name: classmate_db
    volumes:
      - classmate_db:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    env_file:
      - ./.envs/.production/.env.production

volumes:
  classmate_db:
