services:
  web:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    container_name: classmate_web
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - ./.envs/.production/.env.production
      

  db:
    image: postgres:17
    restart: always
    container_name: classmate_db
    volumes:
      - classmate_db:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: classmate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bME1pUGaTl1BFx5vU7ht
    env_file:
      - ./.envs/.production/.env.production
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=bME1pUGaTl1BFx5vU7ht pg_isready -U postgres -d classmate"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  classmate_db:
