# Generated by Django 5.2 on 2025-12-06 09:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0022_academy_cover_image_academy_featured_image_and_more'),
        ('student', '0009_alter_student_birth_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the facility (e.g., Modern Classrooms, Science Labs)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this facility is active/visible')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='academy.academy')),
            ],
            options={
                'verbose_name': 'Academy Facility',
                'verbose_name_plural': 'Academy Facilities',
                'ordering': ['name'],
                'unique_together': {('academy', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AcademyGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Gallery image for the academy', upload_to='academy_gallery/')),
                ('title', models.CharField(blank=True, help_text='Title/caption for the image', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the image', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of images')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this image is active/visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Gallery image creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Gallery image update timestamp')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='academy.academy')),
            ],
            options={
                'verbose_name': 'Academy Gallery Image',
                'verbose_name_plural': 'Academy Gallery Images',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['academy', 'is_active'], name='landingpage_academy_304e79_idx'), models.Index(fields=['order'], name='landingpage_order_eea341_idx')],
            },
        ),
        migrations.CreateModel(
            name='AcademyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Program name (e.g., STEM Programs, Primary Education)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this program is active/visible')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academy.academy')),
            ],
            options={
                'verbose_name': 'Academy Program',
                'verbose_name_plural': 'Academy Programs',
                'ordering': ['name'],
                'unique_together': {('academy', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AcademyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, help_text='Rating out of 5.0', max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('review_text', models.TextField(help_text='Review content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Review creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Review update timestamp')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this review is verified')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this review is approved for display')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this review is active/visible')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='academy.academy')),
                ('student', models.ForeignKey(blank=True, help_text='Student who wrote the review', null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'Academy Review',
                'verbose_name_plural': 'Academy Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['academy', 'is_approved', 'is_active'], name='landingpage_academy_2c9eda_idx'), models.Index(fields=['rating'], name='landingpage_rating_df7a86_idx')],
            },
        ),
    ]
