# Generated by Django 6.0 on 2025-12-07 06:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
        ('student', '0009_alter_student_birth_registration_number'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Achievement title (e.g., Science Educator of the Year 2022)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Achievement description', null=True)),
                ('year', models.CharField(blank=True, choices=[('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039'), ('2040', '2040')], help_text='Year received', max_length=4, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Achievement',
                'verbose_name_plural': 'Teacher Achievements',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='TeacherEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='Degree name (e.g., Ph.D. in Physics, M.Sc. in Chemistry)', max_length=255)),
                ('institution', models.CharField(help_text='Institution name (e.g., Stanford University)', max_length=255)),
                ('year', models.CharField(blank=True, choices=[('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039'), ('2040', '2040')], help_text='Graduation year (e.g., 2025)', max_length=4, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Education',
                'verbose_name_plural': 'Teacher Educations',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='TeacherReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Student name for display', max_length=255)),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(help_text='Review content')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether review is approved by admin')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, help_text='Review submission date')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this review is active/visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Review creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Review update timestamp')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reviews', to='student.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Review',
                'verbose_name_plural': 'Teacher Reviews',
                'ordering': ['-reviewed_at'],
                'unique_together': {('teacher', 'student')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('bangla', 'Bangla'), ('english', 'English'), ('mathematics', 'Mathematics'), ('biology', 'Biology'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('ict', 'Information and Communications Technology'), ('physics_and_chemistry', 'Physics and Chemistry'), ('exam_preparation', 'Exam Preparation'), ('bangla_1st_and_2nd', 'Bangla 1st and 2nd'), ('others', 'Others')], help_text='Subject taught', max_length=100)),
                ('is_primary', models.BooleanField(default=False, help_text="Whether this is the teacher's primary subject")),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Subject',
                'verbose_name_plural': 'Teacher Subjects',
                'ordering': ['-is_primary', 'subject'],
                'unique_together': {('teacher', 'subject')},
            },
        ),
    ]
