# Generated by Django 6.0 on 2025-12-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_teacherachievement_teachereducation_teacherreview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(help_text='Phone number of the person', max_length=20)),
                ('subject', models.CharField(help_text='Subject of the message', max_length=255)),
                ('message', models.TextField(help_text='Message content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Contact us submission timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Contact us update timestamp')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
                'ordering': ['-created_at'],
            },
        ),
    ]
