# Generated by Django 6.0 on 2025-12-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('unreachable', 'Unreachable'), ('completed', 'Completed')], default='pending', max_length=20, null=True),
        ),
    ]
