# Generated by Django 5.2 on 2025-10-29 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('payer_object_id', models.PositiveIntegerField(db_index=True, help_text='ID of the payer object.')),
                ('target_object_id', models.PositiveIntegerField(db_index=True, help_text='ID of the payment target object.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid in this transaction.', max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the payment was made.')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bkash', 'bKash'), ('rocket', 'Rocket'), ('nagad', 'Nagad')], default='cash', help_text='Method used for payment.', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Current status of the payment.', max_length=20)),
                ('transaction_id', models.CharField(blank=True, db_index=True, help_text='External transaction/reference ID, if applicable.', max_length=100)),
                ('remarks', models.TextField(blank=True, help_text='Optional remarks or notes about the payment.')),
                ('reference', models.CharField(blank=True, help_text='Reference ID from external payment system.', max_length=100)),
                ('is_refunded', models.BooleanField(default=False, help_text='Indicates if the payment has been refunded.')),
                ('refund_date', models.DateTimeField(blank=True, help_text='Date when the payment was refunded.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the payment.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('payer_content_type', models.ForeignKey(help_text='Content type of the payer (Student, Academy, Admin, etc.).', on_delete=django.db.models.deletion.CASCADE, related_name='payment_payer_type', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(help_text='Content type of the payment target (Enrollment, Service, etc.).', on_delete=django.db.models.deletion.CASCADE, related_name='payment_target_type', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['payer_content_type', 'payer_object_id'], name='payment_pay_payer_c_0646dc_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='payment_pay_target__055e22_idx'), models.Index(fields=['status'], name='payment_pay_status_124d3d_idx'), models.Index(fields=['transaction_id'], name='payment_pay_transac_f578fa_idx')],
            },
        ),
    ]
