# Generated by Django 5.2 on 2025-11-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_studentpayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='date',
            field=models.DateTimeField(help_text='Timestamp when the payment was made.'),
        ),
    ]
