# Generated by Django 5.2 on 2025-11-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_studentpayment_archived_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpayment',
            name='modified_by',
        ),
    ]
