# Generated by Django 5.2 on 2025-11-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_studentpayment_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
