# Generated by Django 5.2 on 2025-11-11 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0019_remove_batchenrollment_final_grade_delete_grade'),
        ('exam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('title', models.CharField(help_text='Question title or summary', max_length=255)),
                ('question_text', models.TextField(help_text='The actual question text')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay')], default='mcq', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (e.g., "algebra, equations, chapter-1")', max_length=500)),
                ('question_bank_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('suggested_marks', models.DecimalField(decimal_places=2, default=1.0, help_text='Suggested marks for this question', max_digits=5)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this question has been used in exams')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When this question was last used', null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Whether question is approved for use')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expected_answer', models.TextField(blank=True, help_text='Expected answer or answer guidelines')),
                ('marking_scheme', models.TextField(blank=True, help_text='Detailed marking scheme for subjective questions')),
                ('is_active', models.BooleanField(default=True, help_text='Whether question is active and available for use')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bank_questions', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(help_text='Course this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to='academy.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bank_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Bank',
                'verbose_name_plural': 'Question Bank',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('question_text', models.TextField(help_text='The question text')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay')], default='mcq', max_length=20)),
                ('marks', models.DecimalField(decimal_places=2, help_text='Marks for this question', max_digits=5)),
                ('question_order', models.PositiveIntegerField(help_text='Order of question in exam')),
                ('is_required', models.BooleanField(default=True, help_text='Whether this question is mandatory')),
                ('expected_answer', models.TextField(blank=True, help_text='Expected answer (for reference)')),
                ('marking_scheme', models.TextField(blank=True, help_text='Marking scheme for this question')),
                ('question_id', models.CharField(blank=True, editable=False, help_text='Unique ID for the Question', max_length=20, null=True, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.exam')),
                ('question_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_questions', to='question.questionbank')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['exam', 'question_order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBankCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_categories', to='academy.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='question.questionbankcategory')),
            ],
            options={
                'verbose_name': 'Question Category',
                'verbose_name_plural': 'Question Categories',
                'ordering': ['course', 'name'],
            },
        ),
        migrations.AddField(
            model_name='questionbank',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for organizing questions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='question.questionbankcategory'),
        ),
        migrations.CreateModel(
            name='QuestionBankOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('option_text', models.CharField(help_text='Option text', max_length=500)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether this option is correct')),
                ('option_order', models.PositiveIntegerField(help_text='Order of option (1, 2, 3, 4...)')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for why this option is correct/incorrect')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question.questionbank')),
            ],
            options={
                'verbose_name': 'Question Bank Option',
                'verbose_name_plural': 'Question Bank Options',
                'ordering': ['question_bank', 'option_order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('option_text', models.CharField(help_text='Option text', max_length=500)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether this option is correct')),
                ('option_order', models.PositiveIntegerField(help_text='Order of option (A, B, C, D)')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for this option')),
                ('bank_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.questionbankoption')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question.question')),
            ],
            options={
                'verbose_name': 'Question Option',
                'verbose_name_plural': 'Question Options',
                'ordering': ['question', 'option_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('exam', 'question_order'), name='unique_question_order_per_exam'),
        ),
        migrations.AddConstraint(
            model_name='questionbankcategory',
            constraint=models.UniqueConstraint(fields=('course', 'name'), name='unique_category_name_per_course'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['course', 'question_type'], name='question_qu_course__ac9a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['difficulty_level'], name='question_qu_difficu_99bae6_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['is_approved', 'is_active'], name='question_qu_is_appr_e2c183_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionbankoption',
            constraint=models.UniqueConstraint(fields=('question_bank', 'option_order'), name='unique_bank_option_order_per_question'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'option_order'), name='unique_option_order_per_question'),
        ),
    ]
