# Generated by Django 5.2 on 2025-11-11 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionbankcategory',
            options={'ordering': ['name'], 'verbose_name': 'Question Category', 'verbose_name_plural': 'Question Categories'},
        ),
        migrations.RemoveConstraint(
            model_name='questionbankcategory',
            name='unique_category_name_per_course',
        ),
        migrations.RemoveIndex(
            model_name='questionbank',
            name='question_qu_course__ac9a0c_idx',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='course',
        ),
        migrations.RemoveField(
            model_name='questionbankcategory',
            name='course',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='subject',
            field=models.CharField(choices=[('bangla', 'Bangla'), ('english', 'English'), ('mathematics', 'Mathematics'), ('biology', 'Biology'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('ict', 'Information and Communications Technology')], default='bangla', help_text='Subject', max_length=50),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['subject', 'question_type'], name='question_qu_subject_f837e5_idx'),
        ),
    ]
