# Generated by Django 5.2 on 2025-11-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_question_archived_by_questionbank_archived_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='questionbankcategory',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='questionbankoption',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='modified_by',
        ),
    ]
