# Generated by Django 5.2 on 2025-05-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='guardian_contact',
            new_name='guardian_phone',
        ),
    ]
