# Generated by Django 5.2 on 2025-05-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_guardian_contact_student_guardian_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique ID for the student', max_length=20, null=True, unique=True),
        ),
    ]
