# Generated by Django 5.2 on 2025-05-19 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_school_contact_number_school_email_school_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.school'),
        ),
    ]
