# Generated by Django 5.2 on 2025-09-17 00:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='student_stu_student_bb3d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school_id'], name='student_stu_school__06a3ae_idx'),
        ),
    ]
