# Generated by Django 5.2 on 2025-10-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_student_stu_student_bb3d1e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture for the student', null=True, upload_to='student_profiles/'),
        ),
    ]
