# Generated by Django 5.2 on 2025-05-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_registration_number',
            field=models.CharField(blank=True, help_text='Unique birth registration number for the student', max_length=50, null=True, unique=True),
        ),
    ]
