# Generated by Django 5.2 on 2025-05-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
