# Generated by Django 5.2 on 2025-11-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_archived_by_alter_student_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='modified_by',
        ),
    ]
