# Generated by Django 5.2 on 2025-11-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_registration_number',
            field=models.CharField(blank=True, help_text='Unique birth registration number for the student', max_length=50, null=True),
        ),
    ]
