# Generated by Django 6.0 on 2025-12-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_student_birth_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_upload', models.FileField(blank=True, help_text='Upload Excel file with columns: Name, Department, Score', null=True, upload_to='temp_schools/uploads/', verbose_name='Upload Excel for Participants')),
            ],
            options={
                'verbose_name': 'Temp School',
                'verbose_name_plural': 'Temp Schools',
            },
        ),
        migrations.AddField(
            model_name='school',
            name='eiin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
