# Generated by Django 6.0 on 2025-12-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_tempschool_school_eiin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
