# Generated by Django 5.2 on 2025-05-11 10:00

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_initial'),
        ('utils', '0002_division_district_upazila'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='division', chained_model_field='division', null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.district'),
        ),
        migrations.RemoveField(
            model_name='upazila',
            name='district',
        ),
        migrations.AlterField(
            model_name='academy',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.division'),
        ),
        migrations.AlterField(
            model_name='academy',
            name='upazila',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='district', chained_model_field='district', null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.upazila'),
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='Upazila',
        ),
    ]
