# Generated by Django 5.2 on 2025-05-03 07:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academy',
            options={'ordering': ['name'], 'verbose_name': 'Academy', 'verbose_name_plural': 'Academies'},
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['start_date'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batchs'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='academy',
            name='contact_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid contact number.', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='academy',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'academy'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='academy.course'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='academy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academy.academy'),
        ),
    ]
