# Generated by Django 5.2 on 2025-07-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
