# Generated by Django 5.2 on 2025-05-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academy',
            old_name='user',
            new_name='owner',
        ),
    ]
