# Generated by Django 5.2 on 2025-05-11 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_academy_district_remove_upazila_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'academy'}, on_delete=django.db.models.deletion.PROTECT, related_name='academy', to=settings.AUTH_USER_MODEL),
        ),
    ]
