# Generated by Django 5.2 on 2025-05-24 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchenrollment',
            name='final_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.grade'),
        ),
    ]
