# Generated by Django 5.2 on 2025-05-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_alter_batchenrollment_final_grade'),
        ('student', '0002_rename_guardian_contact_student_guardian_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_batches', through='academy.BatchEnrollment', to='student.student'),
        ),
    ]
