# Generated by Django 5.2 on 2025-05-24 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_alter_batch_students'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('name', 'course')},
        ),
    ]
