# Generated by Django 5.2 on 2025-09-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_alter_academy_established_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('bangla', 'Bangla'), ('english', 'English'), ('mathematics', 'Mathematics'), ('biology', 'Biology'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('ict', 'Information and Communications Technology')], default='bangla', help_text='The subject or category this course belongs to', max_length=50),
        ),
    ]
