# Generated by Django 5.2 on 2025-10-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='academy_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique ID for the Academy', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique ID for the Batch', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique ID for the Course', max_length=20, null=True, unique=True),
        ),
    ]
