# Generated by Django 5.2 on 2025-10-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_academy_academy_id_batch_batch_id_course_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='email',
        ),
    ]
