# Generated by Django 5.2 on 2025-10-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_remove_academy_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchenrollment',
            options={'verbose_name': 'Student Enrollment', 'verbose_name_plural': 'Student Enrollments'},
        ),
    ]
