# Generated by Django 5.2 on 2025-11-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_alter_batchenrollment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['start_date'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AddField(
            model_name='batch',
            name='slot_category',
            field=models.CharField(choices=[('jan-jun', 'January to June (6 Months)'), ('jul-dec', 'July to December (6 Months)'), ('jan-apr', 'January to April (4 Months)'), ('may-aug', 'May to August (4 Months)'), ('sep-dec', 'September to December (4 Months)'), ('custom', 'Custom Slot')], default='jan-jun', help_text='Batch duration slot/category', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('bangla', 'Bangla'), ('english', 'English'), ('mathematics', 'Mathematics'), ('biology', 'Biology'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('ict', 'Information and Communications Technology')], default='bangla', help_text='Subject', max_length=50),
        ),
    ]
