# Generated by Django 5.2 on 2025-11-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_alter_batch_options_batch_slot_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchenrollment',
            name='discounted_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted fee for this student. If null, uses the course default fee.', max_digits=10, null=True),
        ),
    ]
