# Generated by Django 5.2 on 2025-11-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_remove_batchenrollment_discounted_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchenrollment',
            name='discount_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Discount fee for this student. If null, uses the course default fee.', max_digits=10, null=True),
        ),
    ]
