# Generated by Django 5.2 on 2025-11-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_alter_batchenrollment_discount_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchenrollment',
            name='discount_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount fee for this student. If null, uses the course default fee.', max_digits=10),
        ),
    ]
