# Generated by Django 5.2 on 2025-11-11 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0018_alter_batchenrollment_discount_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchenrollment',
            name='final_grade',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
