# Generated by Django 5.2 on 2025-11-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0019_remove_batchenrollment_final_grade_delete_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_type',
            new_name='subject',
        ),
    ]
