# Generated by Django 5.2 on 2025-12-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0021_academy_archived_by_batch_archived_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover/banner image for academy', null=True, upload_to='academy_covers/'),
        ),
        migrations.AddField(
            model_name='academy',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for academy cards', null=True, upload_to='academy_featured/'),
        ),
        migrations.AddField(
            model_name='academy',
            name='hours_text',
            field=models.CharField(blank=True, help_text='Contact hours text (e.g., Mon-Fri: 8:00 AM - 5:00 PM)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether this academy is featured on landing page'),
        ),
        migrations.AddField(
            model_name='academy',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short description for academy cards', max_length=500, null=True),
        ),
    ]
