# Generated by Django 6.0 on 2025-12-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0022_academy_cover_image_academy_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(choices=[('bangla', 'Bangla'), ('english', 'English'), ('mathematics', 'Mathematics'), ('biology', 'Biology'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('ict', 'Information and Communications Technology'), ('physics_and_chemistry', 'Physics and Chemistry'), ('exam_preparation', 'Exam Preparation'), ('bangla_1st_and_2nd', 'Bangla 1st and 2nd'), ('others', 'Others')], default='bangla', help_text='Subject', max_length=50),
        ),
    ]
