# Generated by Django 6.0 on 2025-12-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0023_alter_course_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='featured_subject',
            field=models.CharField(blank=True, choices=[('bangla', 'Bangla'), ('english', 'English'), ('mathematics', 'Mathematics'), ('biology', 'Biology'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('ict', 'Information and Communications Technology'), ('physics_and_chemistry', 'Physics and Chemistry'), ('exam_preparation', 'Exam Preparation'), ('bangla_1st_and_2nd', 'Bangla 1st and 2nd'), ('others', 'Others')], help_text='Featured subject', max_length=100, null=True),
        ),
    ]
