# Generated by Django 6.0 on 2025-12-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0025_alter_academy_established_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchenrollment',
            name='followup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchenrollment',
            name='followup_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
