# Generated by Django 5.2 on 2025-05-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=14, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SMSHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text="Recipient's phone number", max_length=15)),
                ('message', models.TextField(help_text='The content of the SMS')),
                ('sms_type', models.CharField(choices=[('OTP', 'One Time Password'), ('Promo', 'Promotional'), ('Notification', 'Notification'), ('Transaction', 'Transactional'), ('Other', 'Other')], default='Other', help_text='Type of SMS', max_length=20)),
                ('status', models.CharField(choices=[('Queue', 'Queue'), ('Sent', 'Sent'), ('Failed', 'Failed'), ('Canceled', 'Canceled')], default='Queue', help_text='Delivery status of the SMS', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the SMS was sent')),
                ('response_at', models.DateTimeField(blank=True, help_text='Timestamp when the SMS was response', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('failed_reason', models.TextField(blank=True, help_text='Reason for failure if SMS sending failed', null=True)),
                ('failed_status_code', models.CharField(blank=True, help_text='Status code returned when SMS failed', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'SMS History',
                'verbose_name_plural': 'SMS Histories',
                'ordering': ['-sent_at'],
            },
        ),
    ]
