# Generated by Django 5.2 on 2025-10-09 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_smshistory_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='smshistory',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='smshistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the SMS record was created', null=True),
        ),
        migrations.AddField(
            model_name='smshistory',
            name='created_for',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sms_history_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smshistory',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the SMS was sent', null=True),
        ),
    ]
