# Generated by Django 5.2 on 2025-10-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_rename_user_smshistory_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smshistory',
            name='sms_type',
            field=models.CharField(choices=[('OTP', 'One Time Password'), ('Promo', 'Promotional'), ('Notification', 'Notification'), ('Transaction', 'Transactional'), ('Account', 'Account Credential'), ('Other', 'Other')], default='Other', help_text='Type of SMS', max_length=20),
        ),
    ]
