# Generated by Django 5.2 on 2025-10-09 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_alter_smshistory_sms_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='smshistory',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smshistory',
            name='created_for',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_history_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
